/**
 * futures-strip.js — Pre-market / live futures & macro data strip
 * Reads data/futures.json (generated by scripts/update_futures.py)
 */
(function() {
  const el = document.getElementById('futures-strip');
  if (!el) return;

  const GROUP_ORDER = ['indices', 'commodities', 'rates', 'volatility', 'crypto'];
  const GROUP_ICONS = {
    indices: '📈', commodities: '🛢️', rates: '🏦', volatility: '⚡', crypto: '₿',
  };

  function render(data) {
    if (!data || !data.quotes || !data.quotes.length) {
      el.style.display = 'none';
      return;
    }

    // Group quotes
    const groups = {};
    for (const q of data.quotes) {
      (groups[q.group] = groups[q.group] || []).push(q);
    }

    let html = '';
    for (const g of GROUP_ORDER) {
      if (!groups[g]) continue;
      html += `<span class="fs-sep">${GROUP_ICONS[g] || '·'}</span>`;
      for (const q of groups[g]) {
        const up = q.changePct >= 0;
        const cls = q.changePct === 0 ? 'fs-flat' : up ? 'fs-up' : 'fs-down';
        const sign = up ? '+' : '';
        const price = q.group === 'crypto' ? `$${q.price.toLocaleString()}` : q.price.toLocaleString();
        html += `<div class="fs-item ${cls}">
          <span class="fs-label">${q.label}</span>
          <span class="fs-price">${price}</span>
          <span class="fs-change">${sign}${q.changePct.toFixed(2)}%</span>
        </div>`;
      }
    }

    // Timestamp
    if (data.updated) {
      const d = new Date(data.updated);
      const t = d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true, timeZone: 'America/New_York' });
      html += `<span class="fs-ts">${t}</span>`;
    }

    el.innerHTML = html;
  }

  fetch('data/futures.json')
    .then(r => r.ok ? r.json() : null)
    .then(render)
    .catch(() => { el.style.display = 'none'; });
})();
